name: Lint Check

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: 'gitmon-client/pnpm-lock.yaml'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
        working-directory: gitmon-client

      - name: Run ESLint Check
        run: pnpm lint
        working-directory: gitmon-client

      - name: Run Prettier Check
        run: npx prettier --check .
        working-directory: gitmon-client
